"Resource/UI/HudAmmoWeapons.res"
{
  "AmmoAnchor"
  {
    "ControlName"     "EditablePanel"
    "fieldName"       "AmmoAnchor"
    "xpos"            "cs-0.5"
    "ypos"            "r92"
    "xpos_minmode"    "c150"
    "ypos_minmode"    "r75"
    "wide"            "20"
    "tall"            "14"
    "wide_minmode"    "30"
    "tall_minmode"    "20"
    "visible"         "1"
    "enabled"         "1"
  }
  "AmmoInClip"
  {
    "ControlName"               "CExLabel"
    "fieldName"                 "AmmoInClip"
    "font"                      "AmmoNumbers"
    "font_minmode"              "AmmoNumbers_MinmodeNormal"
    "fgcolor"                   "255 255 255 255"
    "xpos"                      "22"
    "ypos"                      "0"
    "zpos"                      "5"
    "wide"                      "20"
    "tall"                      "14"
    "wide_minmode"              "35"
    "tall_minmode"              "20"
    "visible"                   "1"
    "enabled"                   "1"
    "textAlignment"             "east"
    "labelText"                 "%Ammo%"
    "pin_to_sibling"            "AmmoAnchor"
  }
  "AmmoInClipShadow"
  {
    "ControlName"               "CExLabel"
    "fieldName"                 "AmmoInClipShadow"
    "font"                      "AmmoNumbers"
    "font_minmode"              "AmmoNumbers_MinmodeNormal"
    "fgcolor"                   "Black"
    "xpos"                      "-1"
    "ypos"                      "-1"
    "zpos"                      "5"
    "wide"                      "20"
    "tall"                      "14"
    "wide_minmode"              "35"
    "tall_minmode"              "20"
    "visible"                   "1"
    "enabled"                   "1"
    "textAlignment"             "east"
    "labelText"                 "%Ammo%"
    "pin_to_sibling"            "AmmoInClip"
  }
  "AmmoInReserve"
  {
    "ControlName"               "CExLabel"
    "fieldName"                 "AmmoInReserve"
    "font"                      "AmmoNumbers"
    "font_minmode"              "AmmoNumbers_MinmodeSub"
    "fgcolor"                   "150 150 150 255"
    "xpos"                      "24"
    "xpos_minmode"              "0"
    "ypos"                      "0"
    "zpos"                      "7"
    "wide"                      "20"
    "tall"                      "14"
    "wide_minmode"              "25"
    "tall_minmode"              "20"
    "visible"                   "0"
    "enabled"                   "1"
    "textAlignment"             "west"
    "textAlignment_minmode"     "south-west"
    "labelText"                 "%AmmoInReserve%"
    "pin_to_sibling"            "AmmoInClip"
    "pin_to_sibling_corner"     "PIN_TOPRIGHT"
    "pin_corner_to_sibling"     "PIN_TOPLEFT"
  }
  "AmmoInReserveShadow"
  {
    "ControlName"               "CExLabel"
    "fieldName"                 "AmmoInReserveShadow"
    "font"                      "AmmoNumbers"
    "font_minmode"              "AmmoNumbers_MinmodeSub"
    "fgcolor"                   "Black"
    "xpos"                      "-1"
    "ypos"                      "-1"
    "zpos"                      "7"
    "wide"                      "20"
    "tall"                      "14"
    "wide_minmode"              "25"
    "tall_minmode"              "20"
    "visible"                   "0"
    "enabled"                   "1"
    "textAlignment"             "west"
    "textAlignment_minmode"     "south-west"
    "labelText"                 "%AmmoInReserve%"
    "pin_to_sibling"            "AmmoInReserve"
  }
  "AmmoNoClip"
  {
    "ControlName"       "CExLabel"
    "fieldName"         "AmmoNoClip"
    "font"              "AmmoNumbers"
    "font_minmode"      "AmmoNumbers_MinmodeNormal"
    "fgcolor"           "255 255 255 255"
    "xpos"              "16"
    "ypos"              "16"
    "xpos_minmode"      "22"
    "ypos_minmode"      "0"
    "zpos"              "5"
    "wide"              "52"
    "tall"              "14"
    "wide_minmode"      "60"
    "tall_minmode"      "20"
    "visible"           "0"
    "enabled"           "1"
    "textAlignment"     "center"
    "labelText"         "%Ammo%"
    "pin_to_sibling"    "AmmoAnchor"
  }
  "AmmoNoClipShadow"
  {
    "ControlName"       "CExLabel"
    "fieldName"         "AmmoNoClipShadow"
    "font"              "AmmoNumbers"
    "font_minmode"      "AmmoNumbers_MinmodeNormal"
    "fgcolor"           "Black"
    "xpos"              "-1"
    "ypos"              "-1"
    "zpos"              "5"
    "wide"              "52"
    "tall"              "14"
    "wide_minmode"      "60"
    "tall_minmode"      "20"
    "visible"           "0"
    "enabled"           "1"
    "textAlignment"     "center"
    "labelText"         "%Ammo%"
    "pin_to_sibling"    "AmmoNoClip"
  }
  ////////////////////////////////////////////////////////////////////////////////////////////////
  // REMOVED
  ////////////////////////////////////////////////////////////////////////////////////////////////
  "HudWeaponAmmoBG"
  {
    "ControlName"       "CTFImagePanel"
    "fieldName"         "HudWeaponAmmoBG"
    "xpos"              "9999"
    "ypos"              "9999"
    "zpos"              "1"
    "wide"              "90"
    "tall"              "45"
    "visible"           "0"
    "enabled"           "1"
    "image"             "../hud/ammo_blue_bg"
    "scaleImage"        "1"
    "teambg_2"          "../hud/ammo_red_bg"
    "teambg_2_lodef"    "../hud/ammo_red_bg_lodef"
    "teambg_3"          "../hud/ammo_blue_bg"
    "teambg_3_lodef"    "../hud/ammo_blue_bg_lodef"
  }
  "HudWeaponLowAmmoImage"
  {
    "ControlName"       "ImagePanel"
    "fieldName"         "HudWeaponLowAmmoImage"
    "xpos"              "9999"
    "ypos"              "9999"
    "zpos"              "0"
    "wide"              "90"
    "tall"              "45"
    "visible"           "0"
    "enabled"           "0"
    "image"             "../hud/ammo_red_bg"
    "scaleImage"        "1"
    "teambg_2"          "../hud/ammo_red_bg"
    "teambg_2_lodef"    "../hud/ammo_red_bg_lodef"
    "teambg_3"          "../hud/ammo_blue_bg"
    "teambg_3_lodef"    "../hud/ammo_blue_bg_lodef"
  }
}