#base "mainmenuoverride_safemode.res"
#base "mainmenuoverride_preload.res"

"Resource/UI/MainMenuOverride.res"
{
  "MainMenuOverride"
  {
    "fieldName"           "MainMenuOverride"
    "visible"             "1"
    "enabled"             "1"
    "xpos"                "0"
    "ypos"                "0"
    "zpos"                "0"
    "wide"                "f0"
    "tall"                "f0"

    "button_x_offset"     "-296"
    "button_y"            "220"
    "button_y_delta"      "1"

    "button_kv"
    {
      "xpos"        "0"
      "ypos"        "0"
      "wide"        "96"
      "tall"        "16"
      "visible"     "1"

      "SubButton"
      {
        "ControlName"                   "CExImageButton"
        "fieldName"                     "SubButton"
        "xpos"                          "0"
        "ypos"                          "0"
        "wide"                          "96"
        "tall"                          "16"
        "autoResize"                    "0"
        "pinCorner"                     "3"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "textinsetx"                    "14"
        "use_proportional_insets"       "1"
        "font"                          "Default"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "default"                       "1"
        "sound_depressed"               "UI/buttonclick.wav"
        "sound_released"                "UI/buttonclickrelease.wav"
        "border_default"                "MainMenuButtonDefault"
        "border_armed"                  "MainMenuButtonArmed"
        "paintbackground"               "0"
        "defaultFgColor_override"       "235 235 235 255"
        "armedFgColor_override"         "45 45 45 255"
        "depressedFgColor_override"     "0 0 0 255"
        "image_drawcolor"               "235 235 235 255"
        "image_armedcolor"              "45 45 45 255"

        "SubImage"
        {
          "ControlName"     "ImagePanel"
          "fieldName"       "SubImage"
          "xpos"            "4"
          "ypos"            "4"
          "zpos"            "1"
          "wide"            "8"
          "tall"            "8"
          "visible"         "1"
          "enabled"         "1"
          "scaleImage"      "1"
        }
      }
    }
  }

  "MainMenuBGPanel"
  {
    "ControlName"             "EditablePanel"
    "fieldName"               "MainMenuBGPanel"
    "xpos"                    "c-306"
    "ypos"                    "210"
    "wide"                    "115"
    "tall"                    "136"
    "visible"                 "1"
		"border"                  "TFThinLineBorder"
  }

  "QuickButtons"
  {
    "ControlName"             "EditablePanel"
    "fieldName"               "QuickButtons"
    "xpos"                    "cs-0.5"
    "ypos"                    "rs1"
    "wide"                    "115"
    "tall"                    "24"
    "visible"                 "0"
    "enabled"                 "0"

    "HudMode_Comp"
    {
      "ControlName"           "EditablePanel"
      "fieldname"             "HudMode_Comp"
      "xpos"                  "0"
      "ypos"                  "0"
      "zpos"                  "1"
      "wide"                  "24"
      "tall"                  "o1"
      "visible"               "1"
      "proportionaltoparent"  "1"

      "SubButton"
      {
        "ControlName"                "CExButton"
        "fieldName"                  "SubButton"
        "xpos"                       "0"
        "ypos"                       "0"
        "wide"                       "f0"
        "tall"                       "f0"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "font"                       "Marlett"
        "textAlignment"              "center"
        "labelText"                  "@"
        "command"                    "engine cl_hud_minmode 1"
        "actionsignallevel"          "3"
        "tooltip"                    "Comp HUD"
        "textAlignment"              "center"
        "sound_depressed"            "UI/buttonclick.wav"
        "sound_released"             "UI/buttonclickrelease.wav"
        "paintbackground"            "1"

        // 102 102 255 255

        // default style
        "defaultBgColor_override"	"Blank"
        "defaultFgColor_override"	"White"
        "border_default"		"NoBorder"

        // armed style
        "armedBgColor_override"	"Blank"
        "armedFgColor_override" 	"102 102 255 255"
        "border_armed"		"NoBorder"

        // depressed style
        "depressedBgColor_override"	"Blank"
        "depressedFgColor_override" "68 68 177 255"
      }
    }

    "HudMode_Centered"
    {
      "ControlName"           "EditablePanel"
      "fieldname"             "HudMode_Centered"
      "xpos"                  "0"
      "ypos"                  "0"
      "zpos"                  "1"
      "wide"                  "24"
      "tall"                  "o1"
      "visible"               "1"
      "proportionaltoparent"  "1"
      "pin_to_sibling"        "HudMode_Comp"
      "pin_corner_to_sibling" "PIN_TOPLEFT"
      "pin_to_sibling_corner" "PIN_TOPRIGHT"

      "SubButton"
      {
        "ControlName"                "CExButton"
        "fieldName"                  "SubButton"
        "xpos"                       "0"
        "ypos"                       "0"
        "wide"                       "f0"
        "tall"                       "f0"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "font"                       "Marlett"
        "textAlignment"              "center"
        "labelText"                  "D"
        "command"                    "engine cl_hud_minmode 0"
        "actionsignallevel"          "3"
        "tooltip"                    "Centered HUD"
        "textAlignment"              "center"
        "sound_depressed"            "UI/buttonclick.wav"
        "sound_released"             "UI/buttonclickrelease.wav"
        "paintbackground"            "1"

        // 102 102 255 255

        // default style
        "defaultBgColor_override"	"Blank"
        "defaultFgColor_override"	"White"
        "border_default"		"NoBorder"

        // armed style
        "armedBgColor_override"	"Blank"
        "armedFgColor_override" 	"102 102 255 255"
        "border_armed"		"NoBorder"

        // depressed style
        "depressedBgColor_override"	"Blank"
        "depressedFgColor_override" "68 68 177 255"
      }
    }
  }


  "MOTDPanel"
  {
    "ControlName"             "EditablePanel"
    "fieldName"               "MOTDPanel"
    "xpos"                    "c0"
    "ypos"                    "102"
    "zpos"                    "0"
    "wide"                    "300"
    "tall"                    "160"
    "visible"                 "0"
    "PaintBackgroundType"     "0"
    "bgcolor_override"        "235 226 202 255"
    "paintbackground"         "0"
    "MOTDBG"
    {
      "ControlName"     "ImagePanel"
      "fieldName"       "MOTDBG"
      "xpos"            "0"
      "ypos"            "0"
      "zpos"            "-99"
      "wide"            "300"
      "tall"            "160"
      "visible"         "1"
      "enabled"         "1"
      "image"           "blog_sheet"
      "scaleImage"      "1"
    }
    "MOTDLabel"
    {
      "ControlName"         "CExLabel"
      "fieldName"           "MOTDLabel"
      "font"                "HudFontSmallestBold"
      "labelText"           "%motddate%"
      "textAlignment"       "center"
      "xpos"                "0"
      "ypos"                "140"
      "wide"                "300"
      "tall"                "10"
      "autoResize"          "0"
      "pinCorner"           "0"
      "visible"             "1"
      "enabled"             "1"
      "fgcolor_override"    "46 43 42 255"
    }
    "PrevMOTDButton"
    {
      "ControlName"         "ImageButton"
      "fieldName"           "PrevMOTDButton"
      "xpos"                "14"
      "ypos"                "138"
      "zpos"                "1"
      "wide"                "20"
      "tall"                "20"
      "autoResize"          "0"
      "pinCorner"           "3"
      "visible"             "1"
      "enabled"             "1"
      "tabPosition"         "0"
      "labelText"           ""
      "font"                "HudFontSmallBold"
      "textAlignment"       "center"
      "dulltext"            "0"
      "brighttext"          "0"
      "default"             "1"
      "Command"             "motd_prev"
      "sound_depressed"     "UI/buttonclick.wav"
      "sound_released"      "UI/buttonclickrelease.wav"
      "paintbackground"     "0"
      "image_drawcolor"     "235 226 202 255"
      "image_armedcolor"    "255 255 255 255"
      "SubImage"
      {
        "ControlName"     "ImagePanel"
        "fieldName"       "SubImage"
        "xpos"            "0"
        "ypos"            "0"
        "zpos"            "1"
        "wide"            "20"
        "tall"            "20"
        "visible"         "1"
        "enabled"         "1"
        "image"           "blog_back"
        "scaleImage"      "1"
      }
    }
    "NextMOTDButton"
    {
      "ControlName"         "ImageButton"
      "fieldName"           "NextMOTDButton"
      "xpos"                "265"
      "ypos"                "136"
      "zpos"                "1"
      "wide"                "20"
      "tall"                "20"
      "autoResize"          "0"
      "pinCorner"           "3"
      "visible"             "1"
      "enabled"             "1"
      "tabPosition"         "0"
      "labelText"           ""
      "font"                "HudFontSmallBold"
      "textAlignment"       "center"
      "dulltext"            "0"
      "brighttext"          "0"
      "default"             "1"
      "Command"             "motd_next"
      "sound_depressed"     "UI/buttonclick.wav"
      "sound_released"      "UI/buttonclickrelease.wav"
      "paintbackground"     "0"
      "image_drawcolor"     "235 226 202 255"
      "image_armedcolor"    "255 255 255 255"
      "SubImage"
      {
        "ControlName"     "ImagePanel"
        "fieldName"       "SubImage"
        "xpos"            "0"
        "ypos"            "0"
        "zpos"            "1"
        "wide"            "20"
        "tall"            "20"
        "visible"         "1"
        "enabled"         "1"
        "image"           "blog_forward"
        "scaleImage"      "1"
      }
    }
    "MOTD_TitleLabel"
    {
      "ControlName"         "CExLabel"
      "fieldName"           "MOTD_TitleLabel"
      "font"                "HudFontSmallBold"
      "labelText"           "%motdtitle%"
      "textAlignment"       "north-west"
      "xpos"                "20"
      "ypos"                "10"
      "wide"                "250"
      "tall"                "30"
      "autoResize"          "0"
      "pinCorner"           "0"
      "visible"             "1"
      "enabled"             "1"
      "fgcolor_override"    "46 43 42 255"
      "wrap"                "1"
    }
    "MOTD_TextScroller"
    {
      "ControlName"             "ScrollableEditablePanel"
      "fieldName"               "MOTD_TextScroller"
      "xpos"                    "20"
      "ypos"                    "40"
      "wide"                    "260"
      "tall"                    "70"
      "PaintBackgroundType"     "2"
      "fgcolor_override"        "117 107 94 255"
      "MOTD_TextPanel"
      {
        "ControlName"             "EditablePanel"
        "fieldName"               "MOTD_TextPanel"
        "xpos"                    "0"
        "ypos"                    "0"
        "wide"                    "250"
        "tall"                    "300"
        "visible"                 "1"
        "PaintBackgroundType"     "2"
        "MOTD_TextLabel"
        {
          "ControlName"         "CExLabel"
          "fieldName"           "MOTD_TextLabel"
          "font"                "HudFontSmall"
          "labelText"           "%motdtext%"
          "textAlignment"       "north-west"
          "xpos"                "0"
          "ypos"                "0"
          "wide"                "250"
          "tall"                "300"
          "autoResize"          "0"
          "pinCorner"           "0"
          "visible"             "1"
          "enabled"             "1"
          "fgcolor_override"    "46 43 42 255"
          "wrap"                "1"
        }
      }
    }
    "MOTD_URLButton"
    {
      "ControlName"                   "CExButton"
      "fieldName"                     "MOTD_URLButton"
      "xpos"                          "75"
      "ypos"                          "112"
      "wide"                          "150"
      "tall"                          "15"
      "autoResize"                    "0"
      "pinCorner"                     "3"
      "visible"                       "1"
      "enabled"                       "1"
      "tabPosition"                   "0"
      "labelText"                     "#MMenu_MOTD_URL"
      "textinsetx"                    "20"
      "use_proportional_insets"       "1"
      "font"                          "HudFontSmallestBold"
      "textAlignment"                 "center"
      "dulltext"                      "0"
      "brighttext"                    "0"
      "default"                       "1"
      "command"                       "motd_viewurl"
      "sound_depressed"               "UI/buttonclick.wav"
      "sound_released"                "UI/buttonclickrelease.wav"
      "defaultFgColor_override"       "235 226 202 255"
      "defaultBgColor_override"       "46 43 42 255"
      "armedFgColor_override"         "235 226 202 255"
      "depressedFgColor_override"     "235 226 202 255"
    }
  }

	"Notifications_ShowButtonPanel"
	{
		"ControlName"							"EditablePanel"
		"fieldName"								"Notifications_ShowButtonPanel"
    "xpos"                    "c-346"
    "ypos"                    "180"
		"zpos"									"12"
		"wide"									"200"
		"tall"									"25"
		"autoResize"							"0"
		"pinCorner"								"3"
		"visible"								"1"
		"enabled"								"1"

		"Notifications_CountLabel"
		{
			"ControlName"						"CExLabel"
			"fieldName"							"Notifications_CountLabel"
			"font"								"Default"
			"labelText"							"%noticount%"
			"textAlignment"						"center"
			"textinsetx"						"6"
			"textinsety"						"0"
			"xpos"								"0"
			"ypos"								"0"
			"zpos"								"4"
			"wide"								"100"
			"tall"								"25"
			"visible"							"0"
			"enabled"							"0"
			"fgcolor_override"					"255 255 255 255"
		}

		"Notifications_ShowButtonPanel_SB"
		{
			"ControlName"						"CExImageButton"
			"fieldName"							"Notifications_ShowButtonPanel_SB"
			"xpos"								"cs-0.5"
			"ypos"								"cs-0.5"
			"zpos"								"1"
			"wide"								"50"
			"tall"								"18"
			"visible"							"1"
			"enabled"							"1"
			"labelText"							"K"
			"font"								"Symbols"
			"textAlignment"						"center"
			// "default"							"1"
			"actionsignallevel" 				"2"
      "proportionaltoparent"  "1"

      "border_default"         "MainMenuBGBorder"
      "border_armed"           "MainMenuBGBorder"

			"Command"							"noti_show"
			"sound_depressed"					"UI/buttonclick.wav"
			"sound_released"					"UI/buttonclickrelease.wav"
		}
	}

  "Notifications_Panel"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Notifications_Panel"
		"xpos"										"c-100"
		"ypos"										"c-200"
		"zpos"										"12"
		"wide"										"205"
		"tall"										"20"
		"visible"									"0"
		"PaintBackgroundType"						"2"
		"paintbackground"							"0"
		"border"									"MainMenuBGBorder"

		"Notifications_CloseButton"
		{
			"ControlName"							"CExImageButton"
			"fieldName"								"Notifications_CloseButton"
			"xpos"									"183"
			"ypos"									"4"
			"zpos"									"10"
			"wide"									"14"
			"tall"									"14"
			"autoResize"							"0"
			"pinCorner"								"0"
			"visible"								"1"
			"enabled"								"1"
			"tabPosition"							"0"
			"labeltext"								"X"
			"font"									"Symbols"
			"textAlignment"							"center"
			"textinsetx"							"1"
			"textinsety"							"-1"
			"dulltext"								"0"
			"brighttext"							"0"
			"default"								"0"
			"actionsignallevel" 					"2"

			"Command"								"noti_hide"

			"paintbackground"						"0"

			"sound_depressed"						"UI/buttonclick.wav"
			"sound_released"						"UI/buttonclickrelease.wav"

			"defaultBgColor_override"				"Blank"
			"armedBgColor_override"					"Blank"
			"depressedBgColor_override" 			"Blank"

			"defaultFgColor_override"				"White"
			"armedFgColor_override"					"White"
			"depressedFgColor_override"				"White"
		}

		"Notifications_TitleLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"Notifications_TitleLabel"
			"font"									"CommonFont10"
			"labelText"								"%notititle%"
			"textAlignment"							"north"
			"xpos"									"7"
			"ypos"									"6"
			"wide"									"250"
			"tall"									"20"
			"autoResize"							"0"
			"pinCorner"								"0"
			"visible"								"1"
			"enabled"								"1"
			"fgcolor"								"White"
			"wrap"									"1"
		}

		"Notifications_Scroller"
		{
			"ControlName"							"ScrollableEditablePanel"
			"fieldName"								"Notifications_Scroller"
			"xpos"									"10"
			"ypos"									"25"
			"wide"									"206"
			"tall"									"100"
			"PaintBackgroundType"					"2"
			"fgcolor_override"						"Black"

			"Notifications_Control"
			{
				"ControlName"						"CMainMenuNotificationsControl"
				"fieldName"							"Notifications_Control"
				"xpos"								"-5"
				"ypos"								"0"
				"wide"								"220"
				"tall"								"100"
				"visible"							"1"
				"fgcolor_override"					"Black"
			}
		}
	}
}
