"resource/ui/mainmenuoverride_safemode.res"
{
  "SafeMode"
  {
    "controlName"     "EditablePanel"
    "fieldName"       "SafeMode"
    "xpos"            "cs-0.5"
    "ypos"            "cs-0.5"
    "wide"            "250"
    "tall"            "150"
    "zpos"            "1000"
    "visible"         "1"
    "enabled"         "1"

    "SafeModeBG"
    {
      "controlName"  "EditablePanel"
      "fieldName"    "SafeModeBG"
      "xpos"         "0"
      "ypos"         "0"
      "wide"         "f0"
      "tall"         "f0"
      "visible"      "1"
      "enabled"      "1"
      "proportionaltoparent" "1"

      "SafeModeBGBase"
      {
        "controlName"          "EditablePanel"
        "fieldName"            "SafeModeBGBase"
        "xpos"                 "0"
        "ypos"                 "0"
        "wide"                 "f0"
        "tall"                 "f0"
        "visible"              "1"
        "enabled"              "1"
        "proportionaltoparent" "1"
        "bgcolor_override"     "TransparentBlack"
      }
      "SafeModeTitle"
      {
        "controlName"          "CExLabel"
        "fieldName"            "SafeModeTitle"
        "xpos"                 "0"
        "ypos"                 "0"
        "wide"                 "f0"
        "tall"                 "12"
        "zpos"                 "2"
        "visible"              "1"
        "enabled"              "1"
        "proportionaltoparent" "1"
        "textAlignment"        "center"
        "fgcolor"              "0 0 0 255"
        "labelText"            "Game Tools"
      }
      "SafeModeTitleBG"
      {
        "controlName"          "EditablePanel"
        "fieldName"            "SafeModeTitleBG"
        "xpos"                 "0"
        "ypos"                 "0"
        "wide"                 "f0"
        "tall"                 "12"
        "zpos"                 "1"
        "visible"              "1"
        "enabled"              "1"
        "proportionaltoparent" "1"
        "bgcolor_override"     "HudPanelBorder"
      }
    }

    "DisplayViewmodels"
    {
      "controlName"           "EditablePanel"
      "fieldName"             "DisplayViewmodels"
      "xpos"                  "0"
      "ypos"                  "12"
      "wide"                  "f0"
      "tall"                  "20"
      "proportionaltoparent"  "1"
      "pin_to_sibling"        "SafeModeTitle"
      "pin_corner_to_sibling" "PIN_TOPLEFT"
      "pin_to_sibling_corner" "PIN_BOTTOMLEFT"

      "DisplayViewmodelsLabel"
      {
        "controlName"           "CExLabel"
        "fieldName"             "DisplayViewmodelsLabel"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "f0-20-20"   // full width - toggle buttons
        "tall"                  "20"
        "visible"               "1"
        "enabled"               "1"
        "proportionaltoparent"  "1"

        "font"                  "HudFontSmallest"
        "textAlignment"         "west"
        "labelText"             "Viewmodels"
        "fgcolor"               "255 255 255 255"
        "textinsetx"            "10"
      }
      "ViewmodelsOff"
      {
        "controlName"                "CExButton"
        "fieldName"                  "ViewmodelsOff"
        "xpos"                       "rs2"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine r_drawviewmodel 0"
        "font"                       "HudFontSmallest"
        "textAlignment"              "center"
        "labelText"                  "0"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
      "ViewmodelsOn"
      {
        "controlName"                "CExButton"
        "fieldName"                  "ViewmodelsOn"
        "xpos"                       "rs1"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine r_drawviewmodel 1"
        "font"                       "HudFontSmallest"
        "textAlignment"              "center"
        "labelText"                  "1"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
    }

    "MinViewmodels"
    {
      "controlName"           "EditablePanel"
      "fieldName"             "MinViewmodels"
      "xpos"                  "0"
      "ypos"                  "0"
      "wide"                  "f0"
      "tall"                  "20"
      "proportionaltoparent"  "1"
      "pin_to_sibling"        "DisplayViewmodels"
      "pin_corner_to_sibling" "PIN_TOPLEFT"
      "pin_to_sibling_corner" "PIN_BOTTOMLEFT"

      "MinViewmodelsLabel"
      {
        "controlName"           "CExLabel"
        "fieldName"             "MinViewmodelsLabel"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "f0-20-20"   // full width - toggle buttons
        "tall"                  "20"
        "visible"               "1"
        "enabled"               "1"
        "proportionaltoparent"  "1"

        "font"                  "HudFontSmallest"
        "textAlignment"         "west"
        "labelText"             "Min Viewmodels"
        "fgcolor"               "255 255 255 255"
        "textinsetx"            "10"
      }

      "MinViewmodelsOff"
      {
        "controlName"                "CExButton"
        "fieldName"                  "MinViewmodelsOff"
        "xpos"                       "rs2"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine tf_use_min_viewmodels 0"
        "font"                       "HudFontSmallest"
        "textAlignment"              "center"
        "labelText"                  "0"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
      "MinViewmodelsOn"
      {
        "controlName"                "CExButton"
        "fieldName"                  "MinViewmodelsOn"
        "xpos"                       "rs1"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine tf_use_min_viewmodels 1"
        "font"                       "HudFontSmallest"
        "textAlignment"              "center"
        "labelText"                  "1"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
    }

    "ViewmodelScale"
    {
      "controlName"           "EditablePanel"
      "fieldName"             "ViewmodelScale"
      "xpos"                  "0"
      "ypos"                  "0"
      "wide"                  "f0"
      "tall"                  "20"
      "proportionaltoparent"  "1"
      "pin_to_sibling"        "MinViewmodels"
      "pin_corner_to_sibling" "PIN_TOPLEFT"
      "pin_to_sibling_corner" "PIN_BOTTOMLEFT"

      "ViewmodelScaleLabel"
      {
        "controlName"           "CExLabel"
        "fieldName"             "ViewmodelScaleLabel"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "125"   // full width - toggle buttons
        "tall"                  "20"
        "visible"               "1"
        "enabled"               "1"
        "proportionaltoparent"  "1"

        "font"                  "HudFontSmallest"
        "textAlignment"         "west"
        "labelText"             "Viewmodel FOV"
        "fgcolor"               "255 255 255 255"
        "textinsetx"            "10"
      }

      "ViewmodelScaleSlider"
      {
        "controlName"                "EditablePanel"
        "fieldName"                  "ViewmodelScaleSlider"
        "xpos"                       "rs1"
        "ypos"                       "0"
        "wide"                       "125"
        "tall"                       "20"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "minvalue"                   "54"
        "maxvalue"                   "110"
        "cvar_name"                  "viewmodel_fov"

        "SettingSlider"
        {
          "controlName"                "CCvarSlider"
          "fieldName"                  "SettingSlider"
          "xpos"                       "rs1"
          "ypos"                       "cs-0.5"
          "wide"                       "f0"
          "tall"                       "f0"
          "visible"                    "1"
          "enabled"                    "1"
          "proportionaltoparent"       "1"
          "minvalue"                   "54"
          "maxvalue"                   "110"
          "cvar_name"                  "viewmodel_fov"
        }
      }
    }

    "Crosshairs"
    {
      "controlName"           "EditablePanel"
      "fieldName"             "Crosshairs"
      "xpos"                  "0"
      "ypos"                  "0"
      "wide"                  "f0"
      "tall"                  "20"
      "proportionaltoparent"  "1"
      "pin_to_sibling"        "ViewmodelScale"
      "pin_corner_to_sibling" "PIN_TOPLEFT"
      "pin_to_sibling_corner" "PIN_BOTTOMLEFT"

      "CrosshairsLabel"
      {
        "controlName"           "CExLabel"
        "fieldName"             "CrosshairsLabel"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "f0-20-20-20-20-20-20-20-20"   // full width - toggle buttons
        "tall"                  "20"
        "visible"               "1"
        "enabled"               "1"
        "proportionaltoparent"  "1"

        "font"                  "HudFontSmallest"
        "textAlignment"         "west"
        "labelText"             "Crosshairs"
        "fgcolor"               "255 255 255 255"
        "textinsetx"            "10"
      }

      "Crosshair_1"
      {
        "controlName"                "CExImageButton"
        "fieldName"                  "Crosshair_1"
        "xpos"                       "rs8"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine cl_crosshair_file crosshair1; cl_crosshair_scale 26"
        "image_drawcolor"            "255 255 255 255"
        "image_armedcolor"           "255 255 255 255"
        "labeltext"                  ""

        "SubImage"
        {
          "controlName"           "ImagePanel"
          "fieldName"             "SubImage"
          "xpos"                  "cs-0.5"
          "ypos"                  "cs-0.5"
          "zpos"                  "1"
          "wide"                  "f-5"
          "tall"                  "f-5"
          "visible"               "1"
          "enabled"               "1"
          "proportionaltoparent"  "1"
          "image"                 "crosshairs/crosshair1"
          "scaleImage"            "1"
        }
      }
      "Crosshair_2"
      {
        "controlName"                "CExImageButton"
        "fieldName"                  "Crosshair_2"
        "xpos"                       "rs7"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine cl_crosshair_file crosshair2; cl_crosshair_scale 26"
        "image_drawcolor"            "255 255 255 255"
        "image_armedcolor"           "255 255 255 255"
        "labeltext"                  ""

        "SubImage"
        {
          "controlName"           "ImagePanel"
          "fieldName"             "SubImage"
          "xpos"                  "cs-0.5"
          "ypos"                  "cs-0.5"
          "zpos"                  "1"
          "wide"                  "f-5"
          "tall"                  "f-5"
          "visible"               "1"
          "enabled"               "1"
          "proportionaltoparent"  "1"
          "image"                 "crosshairs/crosshair2"
          "scaleImage"            "1"
        }
      }
      "Crosshair_3"
      {
        "controlName"                "CExImageButton"
        "fieldName"                  "Crosshair_3"
        "xpos"                       "rs6"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"           "3"
        "command"                    "engine cl_crosshair_file crosshair3; cl_crosshair_scale 32"
        "image_drawcolor"            "255 255 255 255"
        "image_armedcolor"           "255 255 255 255"
        "labeltext"                  ""

        "SubImage"
        {
          "controlName"           "ImagePanel"
          "fieldName"             "SubImage"
          "xpos"                  "cs-0.5"
          "ypos"                  "cs-0.5"
          "zpos"                  "1"
          "wide"                  "f-5"
          "tall"                  "f-5"
          "visible"               "1"
          "enabled"               "1"
          "proportionaltoparent"  "1"
          "image"                 "crosshairs/crosshair3"
          "scaleImage"            "1"
        }
      }
      "Crosshair_4"
      {
        "controlName"                "CExImageButton"
        "fieldName"                  "Crosshair_4"
        "xpos"                       "rs5"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine cl_crosshair_file crosshair4; cl_crosshair_scale 32"
        "image_drawcolor"            "255 255 255 255"
        "image_armedcolor"           "255 255 255 255"
        "labeltext"                  ""

        "SubImage"
        {
          "controlName"           "ImagePanel"
          "fieldName"             "SubImage"
          "xpos"                  "cs-0.5"
          "ypos"                  "cs-0.5"
          "zpos"                  "1"
          "wide"                  "f-5"
          "tall"                  "f-5"
          "visible"               "1"
          "enabled"               "1"
          "proportionaltoparent"  "1"
          "image"                 "crosshairs/crosshair4"
          "scaleImage"            "1"
        }
      }
      "Crosshair_5"
      {
        "controlName"                "CExImageButton"
        "fieldName"                  "Crosshair_5"
        "xpos"                       "rs4"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine cl_crosshair_file crosshair5; cl_crosshair_scale 20"
        "image_drawcolor"            "255 255 255 255"
        "image_armedcolor"           "255 255 255 255"
        "labeltext"                  ""

        "SubImage"
        {
          "controlName"           "ImagePanel"
          "fieldName"             "SubImage"
          "xpos"                  "cs-0.5"
          "ypos"                  "cs-0.5"
          "zpos"                  "1"
          "wide"                  "f-5"
          "tall"                  "f-5"
          "visible"               "1"
          "enabled"               "1"
          "proportionaltoparent"  "1"
          "image"                 "crosshairs/crosshair5"
          "scaleImage"            "1"
        }
      }
      "Crosshair_6"
      {
        "controlName"                "CExImageButton"
        "fieldName"                  "Crosshair_6"
        "xpos"                       "rs3"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine cl_crosshair_file crosshair6; cl_crosshair_scale 26"
        "image_drawcolor"            "255 255 255 255"
        "image_armedcolor"           "255 255 255 255"
        "labeltext"                  ""

        "SubImage"
        {
          "controlName"           "ImagePanel"
          "fieldName"             "SubImage"
          "xpos"                  "cs-0.5"
          "ypos"                  "cs-0.5"
          "zpos"                  "1"
          "wide"                  "f-5"
          "tall"                  "f-5"
          "visible"               "1"
          "enabled"               "1"
          "proportionaltoparent"  "1"
          "image"                 "crosshairs/crosshair6"
          "scaleImage"            "1"
        }
      }
      "Crosshair_7"
      {
        "controlName"                "CExImageButton"
        "fieldName"                  "Crosshair_7"
        "xpos"                       "rs2"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine cl_crosshair_file crosshair7; cl_crosshair_scale 26"
        "image_drawcolor"            "255 255 255 255"
        "image_armedcolor"           "255 255 255 255"
        "labeltext"                  ""

        "SubImage"
        {
          "controlName"           "ImagePanel"
          "fieldName"             "SubImage"
          "xpos"                  "cs-0.5"
          "ypos"                  "cs-0.5"
          "zpos"                  "1"
          "wide"                  "f-5"
          "tall"                  "f-5"
          "visible"               "1"
          "enabled"               "1"
          "proportionaltoparent"  "1"
          "image"                 "crosshairs/crosshair7"
          "scaleImage"            "1"
        }
      }
      "Crosshair_Default"
      {
        "controlName"                "CExImageButton"
        "fieldName"                  "Crosshair_Default"
        "xpos"                       "rs1"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine cl_crosshair_file default; cl_crosshair_scale 26"
        "image_drawcolor"            "255 255 255 255"
        "image_armedcolor"           "255 255 255 255"
        "labeltext"                  ""

        "SubImage"
        {
          "controlName"           "ImagePanel"
          "fieldName"             "SubImage"
          "xpos"                  "cs-0.5"
          "ypos"                  "cs-0.5"
          "zpos"                  "1"
          "wide"                  "f4"
          "tall"                  "f4"
          "visible"               "1"
          "enabled"               "1"
          "proportionaltoparent"  "1"
          "image"                 "crosshairs/default"
          "scaleImage"            "1"
        }
      }
    }

    "TextChat"
    {
      "controlName"           "EditablePanel"
      "fieldName"             "TextChat"
      "xpos"                  "0"
      "ypos"                  "0"
      "wide"                  "f0"
      "tall"                  "20"
      "proportionaltoparent"  "1"
      "pin_to_sibling"        "Crosshairs"
      "pin_corner_to_sibling" "PIN_TOPLEFT"
      "pin_to_sibling_corner" "PIN_BOTTOMLEFT"

      "TextChatLabel"
      {
        "controlName"           "CExLabel"
        "fieldName"             "TextChatLabel"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "f0-20-20"   // full width - toggle buttons
        "tall"                  "20"
        "visible"               "1"
        "enabled"               "1"
        "proportionaltoparent"  "1"

        "font"                  "HudFontSmallest"
        "textAlignment"         "west"
        "labelText"             "Text Chat"
        "fgcolor"               "255 255 255 255"
        "textinsetx"            "10"
      }

      "TextChatOff"
      {
        "controlName"                "CExButton"
        "fieldName"                  "TextChatOff"
        "xpos"                       "rs2"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine hud_saytext_time 0"
        "font"                       "HudFontSmallest"
        "textAlignment"              "center"
        "labelText"                  "0"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
      "TextChatOn"
      {
        "controlName"                "CExButton"
        "fieldName"                  "TextChatOn"
        "xpos"                       "rs1"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine hud_saytext_time 6"
        "font"                       "HudFontSmallest"
        "textAlignment"              "center"
        "labelText"                  "1"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
    }

    "VoiceChat"
    {
      "controlName"           "EditablePanel"
      "fieldName"             "VoiceChat"
      "xpos"                  "0"
      "ypos"                  "0"
      "wide"                  "f0"
      "tall"                  "20"
      "proportionaltoparent"  "1"
      "pin_to_sibling"        "TextChat"
      "pin_corner_to_sibling" "PIN_TOPLEFT"
      "pin_to_sibling_corner" "PIN_BOTTOMLEFT"

      "VoiceChatLabel"
      {
        "controlName"           "CExLabel"
        "fieldName"             "VoiceChatLabel"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "f0-20-20"   // full width - toggle buttons
        "tall"                  "20"
        "visible"               "1"
        "enabled"               "1"
        "proportionaltoparent"  "1"

        "font"                  "HudFontSmallest"
        "textAlignment"         "west"
        "labelText"             "Voice Chat"
        "fgcolor"               "255 255 255 255"
        "textinsetx"            "10"
      }

      "VoiceChatOff"
      {
        "controlName"                "CExButton"
        "fieldName"                  "VoiceChatOff"
        "xpos"                       "rs2"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine voice_modenable 0"
        "font"                       "HudFontSmallest"
        "textAlignment"              "center"
        "labelText"                  "0"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
      "VoiceChatOn"
      {
        "controlName"                "CExButton"
        "fieldName"                  "VoiceChatOn"
        "xpos"                       "rs1"
        "ypos"                       "0"
        "wide"                       "20"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine voice_modenable 1"
        "font"                       "HudFontSmallest"
        "textAlignment"              "center"
        "labelText"                  "1"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
    }

    "CustomCommands"
    {
      "controlName"           "EditablePanel"
      "fieldName"             "CustomCommands"
      "xpos"                  "0"
      "ypos"                  "0"
      "wide"                  "f0"
      "tall"                  "20"
      "proportionaltoparent"  "1"
      "pin_to_sibling"        "VoiceChat"
      "pin_corner_to_sibling" "PIN_TOPLEFT"
      "pin_to_sibling_corner" "PIN_BOTTOMLEFT"

      "CustomCommandLabel"
      {
        "controlName"           "CExLabel"
        "fieldName"             "CustomCommandLabel"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "90"   // full width - toggle buttons
        "tall"                  "16"
        "visible"               "1"
        "enabled"               "1"
        "proportionaltoparent"  "1"

        "font"                  "HudFontSmallest"
        "textAlignment"         "west"
        "labelText"             "Aliases"
        "fgcolor"               "255 255 255 255"
        "textinsetx"            "10"
      }

      "CustomCommand01"
      {
        "controlName"                "CExButton"
        "fieldName"                  "CustomCommand01"
        "xpos"                       "0"
        "ypos"                       "0"
        "wide"                       "16"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "pin_to_sibling"             "CustomCommandLabel"
        "pin_to_sibling_corner"      "PIN_TOPRIGHT"
        "pin_corner_to_sibling"      "PIN_TOPLEFT"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine /1"
        "font"                       "FontStoreOriginalPrice"
        "textAlignment"              "center"
        "labelText"                  "01"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
      "CustomCommand02"
      {
        "controlName"                "CExButton"
        "fieldName"                  "CustomCommand02"
        "xpos"                       "0"
        "ypos"                       "0"
        "wide"                       "16"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "pin_to_sibling"             "CustomCommand01"
        "pin_to_sibling_corner"      "PIN_TOPRIGHT"
        "pin_corner_to_sibling"      "PIN_TOPLEFT"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine /2"
        "font"                       "FontStoreOriginalPrice"
        "textAlignment"              "center"
        "labelText"                  "02"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
      "CustomCommand03"
      {
        "controlName"                "CExButton"
        "fieldName"                  "CustomCommand03"
        "xpos"                       "0"
        "ypos"                       "0"
        "wide"                       "16"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "pin_to_sibling"             "CustomCommand02"
        "pin_to_sibling_corner"      "PIN_TOPRIGHT"
        "pin_corner_to_sibling"      "PIN_TOPLEFT"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine /3"
        "font"                       "FontStoreOriginalPrice"
        "textAlignment"              "center"
        "labelText"                  "03"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
      "CustomCommand04"
      {
        "controlName"                "CExButton"
        "fieldName"                  "CustomCommand04"
        "xpos"                       "0"
        "ypos"                       "0"
        "wide"                       "16"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "pin_to_sibling"             "CustomCommand03"
        "pin_to_sibling_corner"      "PIN_TOPRIGHT"
        "pin_corner_to_sibling"      "PIN_TOPLEFT"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine /4"
        "font"                       "FontStoreOriginalPrice"
        "textAlignment"              "center"
        "labelText"                  "04"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
      "CustomCommand05"
      {
        "controlName"                "CExButton"
        "fieldName"                  "CustomCommand05"
        "xpos"                       "0"
        "ypos"                       "0"
        "wide"                       "16"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "pin_to_sibling"             "CustomCommand04"
        "pin_to_sibling_corner"      "PIN_TOPRIGHT"
        "pin_corner_to_sibling"      "PIN_TOPLEFT"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine /5"
        "font"                       "FontStoreOriginalPrice"
        "textAlignment"              "center"
        "labelText"                  "05"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
      "CustomCommand06"
      {
        "controlName"                "CExButton"
        "fieldName"                  "CustomCommand06"
        "xpos"                       "0"
        "ypos"                       "0"
        "wide"                       "16"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "pin_to_sibling"             "CustomCommand05"
        "pin_to_sibling_corner"      "PIN_TOPRIGHT"
        "pin_corner_to_sibling"      "PIN_TOPLEFT"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine /6"
        "font"                       "FontStoreOriginalPrice"
        "textAlignment"              "center"
        "labelText"                  "06"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
      "CustomCommand07"
      {
        "controlName"                "CExButton"
        "fieldName"                  "CustomCommand07"
        "xpos"                       "0"
        "ypos"                       "0"
        "wide"                       "16"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "pin_to_sibling"             "CustomCommand06"
        "pin_to_sibling_corner"      "PIN_TOPRIGHT"
        "pin_corner_to_sibling"      "PIN_TOPLEFT"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine /7"
        "font"                       "FontStoreOriginalPrice"
        "textAlignment"              "center"
        "labelText"                  "07"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
      "CustomCommand08"
      {
        "controlName"                "CExButton"
        "fieldName"                  "CustomCommand08"
        "xpos"                       "s0"
        "ypos"                       "0"
        "wide"                       "16"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "pin_to_sibling"             "CustomCommand07"
        "pin_to_sibling_corner"      "PIN_TOPRIGHT"
        "pin_corner_to_sibling"      "PIN_TOPLEFT"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine /8"
        "font"                       "FontStoreOriginalPrice"
        "textAlignment"              "center"
        "labelText"                  "08"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
      "CustomCommand09"
      {
        "controlName"                "CExButton"
        "fieldName"                  "CustomCommand09"
        "xpos"                       "s0"
        "ypos"                       "0"
        "wide"                       "16"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "pin_to_sibling"             "CustomCommand08"
        "pin_to_sibling_corner"      "PIN_TOPRIGHT"
        "pin_corner_to_sibling"      "PIN_TOPLEFT"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine /9"
        "font"                       "FontStoreOriginalPrice"
        "textAlignment"              "center"
        "labelText"                  "09"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
      "CustomCommand10"
      {
        "controlName"                "CExButton"
        "fieldName"                  "CustomCommand10"
        "xpos"                       "s0"
        "ypos"                       "0"
        "wide"                       "16"
        "tall"                       "o1"
        "visible"                    "1"
        "enabled"                    "1"
        "pin_to_sibling"             "CustomCommand09"
        "pin_to_sibling_corner"      "PIN_TOPRIGHT"
        "pin_corner_to_sibling"      "PIN_TOPLEFT"
        "proportionaltoparent"       "1"
        "sound_depressed"            "UI/buttonclick.wav"
        "actionsignallevel"          "3"
        "command"                    "engine /10"
        "font"                       "FontStoreOriginalPrice"
        "textAlignment"              "center"
        "labelText"                  "10"
        "fgcolor"                    "255 255 255 255"
        "defaultFgColor_override"    "255 255 255 255"
        "armedFgColor_override"      "000 133 199 240"
        "depressedFgColor_override"  "050 050 050 255"
      }
    }
  }
}
